
const movieQuotes = [
  { rank: 1, quote: "Frankly, my dear, I don't give a damn.", movie: "Gone With the Wind", year: 1939 },
  { rank: 2, quote: "I'm going to make him an offer he can't refuse.", movie: "The Godfather", year: 1972 },
  { rank: 3, quote: "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody", movie: "On the Waterfront", year: 1954 },
  { rank: 4, quote: "Toto, I've got a feeling we're not in Kansas anymore.", movie: "The Wizard of Oz", year: 1939 },
  { rank: 5, quote: "Here's looking at you, kid.", movie: "Casablanca", year: 1942 },
  { rank: 6, quote: "Go ahead, make my day.", movie: "Sudden Impact", year: 1983 },
  { rank: 7, quote: "All right, Mr. DeMille, I'm ready for my close-up.", movie: "Sunset Blvd.", year: 1950 },
  { rank: 8, quote: "May the Force be with you.", movie: "Star Wars", year: 1977 },
  { rank: 9, quote: "Fasten your seatbelts. It's going to be a bumpy night.", movie: "All About Eve", year: 1950 },
  { rank: 10, quote: "You talking to me?", movie: "Taxi Driver", year: 1976 },
  { rank: 11, quote: "What we've got here is failure to communicate.", movie: "Cool Hand Luke", year: 1967 },
  { rank: 12, quote: "I love the smell of napalm in the morning.", movie: "Apocalypse Now", year: 1979 },
  { rank: 13, quote: "Love means never having to say you're sorry.", movie: "Love Story", year: 1970 },
  { rank: 14, quote: "The stuff that dreams are made of.", movie: "The Maltese Falcon", year: 1941 },
  { rank: 15, quote: "E.T. phone home.", movie: "E.T. the Extra Terrestrial", year: 1982 },
  { rank: 16, quote: "They call me Mister Tibbs!", movie: "In the Heat of the Night", year: 1967 },
  { rank: 17, quote: "Rosebud.", movie: "Citizen Kane", year: 1941 },
  { rank: 18, quote: "Made it, Ma! Top of the world!", movie: "White Heat", year: 1949 },
  { rank: 19, quote: "I'm as mad as hell, and I'm not going to take this anymore!", movie: "Network", year: 1976 },
  { rank: 20, quote: "Louis, I think this is the beginning of a beautiful friendship.", movie: "Casablanca", year: 1942 },
  { rank: 21, quote: "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", movie: "The Silence of the Lambs", year: 1991 },
  { rank: 22, quote: "Bond. James Bond.", movie: "Dr. No", year: 1962 },
  { rank: 23, quote: "There's no place like home.", movie: "The Wizard of Oz", year: 1939 },
  { rank: 24, quote: "I am big! It's the pictures that got small.", movie: "Sunset Blvd.", year: 1950 },
  { rank: 25, quote: "Show me the money!", movie: "Jerry Maguire", year: 1996 },
  { rank: 26, quote: "Why don't you come up sometime and see me?", movie: "She Done Him Wrong", year: 1933 },
  { rank: 27, quote: "I'm walking here! I'm walking here!", movie: "Midnight Cowboy", year: 1969 },
  { rank: 28, quote: "Play it, Sam. Play 'As Time Goes By.'", movie: "Casablanca", year: 1942 },
  { rank: 29, quote: "You can't handle the truth!", movie: "A Few Good Men", year: 1992 },
  { rank: 30, quote: "I want to be alone.", movie: "Grand Hotel", year: 1932 },
  { rank: 31, quote: "After all, tomorrow is another day!", movie: "Gone With the Wind", year: 1939 },
  { rank: 32, quote: "Round up the usual suspects.", movie: "Casablanca", year: 1942 },
  { rank: 33, quote: "I'll have what she's having.", movie: "When Harry Met Sally", year: 1989 },
  { rank: 34, quote: "You know how to whistle, don't you, Steve? You just put your lips together and blow.", movie: "To Have and to Have Not", year: 1944 },
  { rank: 35, quote: "You're gonna need a bigger boat.", movie: "Jaws", year: 1975 },
  { rank: 36, quote: "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!", movie: "The Treasure of the Sierra Madre", year: 1948 },
  { rank: 37, quote: "I'll be back.", movie: "The Terminator", year: 1984 },
  { rank: 38, quote: "Today, I consider myself the luckiest man on the face of the earth.", movie: "The Pride of the Yankees", year: 1942 },
  { rank: 39, quote: "If you build it, he will come.", movie: "Field of Dreams", year: 1989 },
  { rank: 40, quote: "Mama always said life was like a box of chocolates. You never know what you're gonna get.", movie: "Forrest Gump", year: 1994 },
  { rank: 41, quote: "We rob banks.", movie: "Bonnie and Clyde", year: 1967 },
  { rank: 42, quote: "Plastics.", movie: "The Graduate", year: 1967 },
  { rank: 43, quote: "We'll always have Paris.", movie: "Casablanca", year: 1942 },
  { rank: 44, quote: "I see dead people.", movie: "The Sixth Sense", year: 1999 },
  { rank: 45, quote: "Stella! Hey, Stella!", movie: "A Streetcar Named Desire", year: 1951 },
  { rank: 46, quote: "Oh, Jerry, don't let's ask for the moon. We have the stars.", movie: "Now, Voyager", year: 1942 },
  { rank: 47, quote: "Shane. Shane. Come back!", movie: "Shane", year: 1953 },
  { rank: 48, quote: "Well, nobody's perfect.", movie: "Some Like It Hot", year: 1959 },
  { rank: 49, quote: "It's alive! It's alive!", movie: "Frankenstein", year: 1931 },
  { rank: 50, quote: "Houston, we have a problem.", movie: "Apollo 13", year: 1995 },
  { rank: 51, quote: "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?", movie: "Dirty Harry", year: 1971 },
  { rank: 52, quote: 'You had me at "hello."', movie: "Jerry Maguire", year: 1996 },
  { rank: 53, quote: "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.", movie: "Animal Crackers", year: 1930 },
  { rank: 54, quote: "There's no crying in baseball!", movie: "A League of Their Own", year: 1992 },
  { rank: 55, quote: "La-dee-da, la-dee-da.", movie: "Annie Hall", year: 1977 },
  { rank: 56, quote: "A boy's best friend is his mother.", movie: "Psycho", year: 1960 },
  { rank: 57, quote: "Greed, for lack of a better word, is good.", movie: "Wall Street", year: 1987 },
  { rank: 58, quote: "Keep your friends close, but your enemies closer.", movie: "The Godfather II", year: 1974 },
  { rank: 59, quote: "As God is my witness, I'll never be hungry again.", movie: "Gone with the Wind", year: 1939 },
  { rank: 60, quote: "Well, here's another nice mess you've gotten me into!", movie: "Sons of the Desert", year: 1933 },
  { rank: 61, quote: 'Say "hello" to my little friend!', movie: "Scarface", year: 1983 },
  { rank: 62, quote: "What a dump.", movie: "Beyond the Forest", year: 1949 },
  { rank: 63, quote: "Mrs. Robinson, you're trying to seduce me. Aren't you?", movie: "The Graduate", year: 1967 },
  { rank: 64, quote: "Gentlemen, you can't fight in here! This is the War Room!", movie: "Dr. Strangelove", year: 1964 },
  { rank: 65, quote: "Elementary, my dear Watson.", movie: "The Adventures of Sherlock Holmes", year: 1929 },
  { rank: 66, quote: "Get your stinking paws off me, you damned dirty ape.", movie: "Planet of the Apes", year: 1968 },
  { rank: 67, quote: "Of all the gin joints in all the towns in all the world, she walks into mine.", movie: "Casablanca", year: 1942 },
  { rank: 68, quote: "Here's Johnny!", movie: "The Shining", year: 1980 },
  { rank: 69, quote: "They're here!", movie: "Poltergeist", year: 1982 },
  { rank: 70, quote: "Is it safe?", movie: "Marathon Man", year: 1976 },
  { rank: 71, quote: "Wait a minute, wait a minute. You ain't heard nothin' yet!", movie: "The Jazz Singer", year: 1927 },
  { rank: 72, quote: "No wire hangers, ever!", movie: "Mommie Dearest", year: 1981 },
  { rank: 73, quote: "Mother of mercy, is this the end of Rico?", movie: "Little Caesar", year: 1930 },
  { rank: 74, quote: "Forget it, Jake, it's Chinatown.", movie: "Chinatown", year: 1974 },
  { rank: 75, quote: "I have always depended on the kindness of strangers.", movie: "A Streetcar Named Desire", year: 1951 },
  { rank: 76, quote: "Hasta la vista, baby.", movie: "Terminator 2: Judgement Day", year: 1991 },
  { rank: 77, quote: "Soylent Green is people!", movie: "Soylent Green", year: 1973 },
  { rank: 78, quote: "Open the pod bay doors, HAL.", movie: "2001: A Space Odyssey", year: 1968 },
  { rank: 79, quote: "Striker: Surely you can't be serious. Rumack: I am serious...and don't call me Shirley.", movie: "Airplane!", year: 1980 },
  { rank: 80, quote: "Yo, Adrian!", movie: "Rocky", year: 1976 },
  { rank: 81, quote: "Hello, gorgeous.", movie: "Funny Girl", year: 1968 },
  { rank: 82, quote: "Toga! Toga!", movie: "National Lampoon's Animal House", year: 1978 },
  { rank: 83, quote: "Listen to them. Children of the night. What music they make.", movie: "Dracula", year: 1931 },
  { rank: 84, quote: "Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.", movie: "King Kong", year: 1933 },
  { rank: 85, quote: "My precious.", movie: "The Lord of the Rings: Two Towers", year: 2002 },
  { rank: 86, quote: "Attica! Attica!", movie: "Dog Day Afternoon", year: 1975 },
  { rank: 87, quote: "Sawyer, you're going out a youngster, but you've got to come back a star!", movie: "42nd Street", year: 1933 },
  { rank: 88, quote: "Listen to me, mister. You're my knight in shining armor. Don't you forget it. ", movie: "On Golden Pond", year: 1981 },
  { rank: 89, quote: "Tell 'em to go out there with all they got and win just one for the Gipper.", movie: "Knute Rockne All American", year: 1940 },
  { rank: 90, quote: "A martini. Shaken, not stirred.", movie: "Goldfinger", year: 1964 },
  { rank: 91, quote: "Who's on first.", movie: "The Naughty Nineties", year: 1945 },
  { rank: 92, quote: "Cinderella story. Outta nowhere.", movie: "Caddyshack", year: 1980 },
  { rank: 93, quote: "Life is a banquet, and most poor suckers are starving to death!", movie: "Auntie Mame", year: 1958 },
  { rank: 94, quote: "I feel the need — the need for speed!", movie: "Top Gun", year: 1986 },
  { rank: 95, quote: "Carpe diem. Seize the day, boys. Make your lives extraordinary.", movie: "Dead Poets Society", year: 1989 },
  { rank: 96, quote: "Snap out of it!", movie: "Moonstruck", year: 1987 },
  { rank: 97, quote: "My mother thanks you. My father thanks you. My sister thanks you. And I thank you.", movie: "Yankee Doodle Dandy", year: 1942 },
  { rank: 98, quote: "Nobody puts Baby in a corner.", movie: "Dirty Dancing", year: 1987 },
  { rank: 99, quote: "I'll get you, my pretty, and your little dog, too!", movie: "The Wizard of Oz", year: 1939 },
  { rank: 100, quote: "I'm king of the world!", movie: "Titanic", year: 1997 },
];

export default movieQuotes;